; Proyecto de ejemplo: mover un servo SG90 con el teclado (Arduino UNO)
; Aprendemos comunicacion serial: la compu manda teclas y la placa mueve el servo.

[env:uno]
platform = atmelavr@5.2.0  ; version fijada EXACTA (sin ^ ni ~): mismo binario para todos, instalen cuando instalen
board = uno              ; tipo de placa
framework = arduino      ; framework Arduino (setup/loop)
monitor_speed = 9600     ; velocidad del monitor serial
lib_deps = arduino-libraries/Servo   ; libreria del servo (PlatformIO no la trae sola)
