; Proyecto de ejemplo: hacer parpadear el LED integrado del Arduino UNO
; Este es el "Hola mundo" de la electronica.

[env:uno]
platform = atmelavr      ; plataforma para Arduino UNO y Nano
board = uno              ; tipo de placa
framework = arduino      ; framework Arduino (setup/loop)
monitor_speed = 9600     ; velocidad del monitor serial
