; Proyecto de ejemplo: mover un servo SG90 con el teclado (ESP32-DevKitC)
; Aprendemos comunicacion serial: la compu manda teclas y la placa mueve el servo.

[env:esp32dev]
platform = espressif32          ; plataforma para chips ESP32
board = esp32dev                ; ESP32-DevKitC / WROOM-32 generico
framework = arduino             ; framework Arduino (setup/loop)
monitor_speed = 115200          ; velocidad del monitor serial (ESP32 usa 115200)
lib_deps = madhephaestus/ESP32Servo  ; en ESP32 la libreria Servo NO viene incluida
