; Proyecto de ejemplo para ESP32-DevKitC (Espressif, chip ESP32-WROOM-32)
; Hace parpadear GPIO2 y manda mensajes por el monitor serial.

[env:esp32dev]
platform = espressif32     ; plataforma para chips ESP32
board = esp32dev           ; ESP32-DevKitC / WROOM-32 generico
framework = arduino        ; framework Arduino (setup/loop)
monitor_speed = 115200     ; velocidad del monitor serial (ESP32 usa 115200)
